/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import controle.ControladorCadastroUsuário;
import entidade.FichaCadastro;
import entidade.Usuario;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Marco Antonio
 */
public class JanelaCadastroUsuário extends javax.swing.JFrame {

    ControladorCadastroUsuário controlador;

    /**
     * Creates new form JanelaCadastoUsuario
     */
    public JanelaCadastroUsuário(ControladorCadastroUsuário controlador) {
        this.controlador = controlador;
        initComponents();
        salvarButton.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dadosPanel = new javax.swing.JPanel();
        codigoLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        cargoLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        confirma_senhaLabel = new javax.swing.JLabel();
        cod_usuarioTextField = new javax.swing.JTextField();
        nome_usuarioTextField = new javax.swing.JTextField();
        senhaPasswordField = new javax.swing.JPasswordField();
        confirma_senhaPasswordField = new javax.swing.JPasswordField();
        cargoComboBox = new javax.swing.JComboBox();
        botões_fornecedorPanel = new javax.swing.JPanel();
        eliminarButton = new javax.swing.JButton();
        novoButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        gravarButton = new javax.swing.JButton();
        editar_Button = new javax.swing.JButton();
        salvarButton = new javax.swing.JButton();
        cancelaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Usuário");
        setResizable(false);

        dadosPanel.setBackground(new java.awt.Color(255, 255, 255));
        dadosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Cadastro de Usuários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 12))); // NOI18N

        codigoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        codigoLabel.setText("Codigo");

        nomeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomeLabel.setText("Nome");

        cargoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cargoLabel.setText("Cargo");

        senhaLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        senhaLabel.setText("Senha");

        confirma_senhaLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        confirma_senhaLabel.setText("Confirme a Senha");

        cod_usuarioTextField.setEditable(false);
        cod_usuarioTextField.setEnabled(false);

        nome_usuarioTextField.setEnabled(false);

        senhaPasswordField.setEnabled(false);

        confirma_senhaPasswordField.setEnabled(false);

        cargoComboBox.setModel(new DefaultComboBoxModel(FichaCadastro.Cargo.values()));
        cargoComboBox.setEnabled(false);

        botões_fornecedorPanel.setBackground(new java.awt.Color(255, 255, 255));

        eliminarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.setEnabled(false);
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        novoButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        novoButton.setText("Novo");
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });

        consultarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarButtonActionPerformed(evt);
            }
        });

        gravarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gravarButton.setText("Gravar");
        gravarButton.setEnabled(false);
        gravarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravarButtonActionPerformed(evt);
            }
        });

        editar_Button.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editar_Button.setText("Editar");
        editar_Button.setEnabled(false);
        editar_Button.setMaximumSize(new java.awt.Dimension(63, 23));
        editar_Button.setMinimumSize(new java.awt.Dimension(63, 23));
        editar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_ButtonActionPerformed(evt);
            }
        });

        salvarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        cancelaButton.setText("Cancela");
        cancelaButton.setEnabled(false);
        cancelaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botões_fornecedorPanelLayout = new javax.swing.GroupLayout(botões_fornecedorPanel);
        botões_fornecedorPanel.setLayout(botões_fornecedorPanelLayout);
        botões_fornecedorPanelLayout.setHorizontalGroup(
            botões_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botões_fornecedorPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(novoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gravarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelaButton))
        );
        botões_fornecedorPanelLayout.setVerticalGroup(
            botões_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botões_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(gravarButton)
                .addComponent(consultarButton)
                .addComponent(editar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(salvarButton)
                .addComponent(eliminarButton)
                .addComponent(novoButton)
                .addComponent(cancelaButton))
        );

        javax.swing.GroupLayout dadosPanelLayout = new javax.swing.GroupLayout(dadosPanel);
        dadosPanel.setLayout(dadosPanelLayout);
        dadosPanelLayout.setHorizontalGroup(
            dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPanelLayout.createSequentialGroup()
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosPanelLayout.createSequentialGroup()
                        .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dadosPanelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nomeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cargoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(senhaLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(dadosPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(confirma_senhaLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome_usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(confirma_senhaPasswordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(senhaPasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cod_usuarioTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosPanelLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(botões_fornecedorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dadosPanelLayout.setVerticalGroup(
            dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel)
                    .addComponent(cod_usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nome_usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargoLabel)
                    .addComponent(cargoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaLabel)
                    .addComponent(senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirma_senhaLabel)
                    .addComponent(confirma_senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botões_fornecedorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dadosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dadosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void limpa() {
        nome_usuarioTextField.setText("");
        cargoComboBox.setSelectedIndex(0);
        senhaPasswordField.setText("");
        confirma_senhaPasswordField.setText("");
    }

    public static void editarSalvar() {
        salvarButton.setVisible(false);
        editar_Button.setVisible(true);
    }

    public static void setEdição(boolean estado) {
        nome_usuarioTextField.setEditable(estado);
        cargoComboBox.setEditable(estado);
        senhaPasswordField.setEditable(estado);
        confirma_senhaPasswordField.setEditable(estado);
    }

    public static void setAtivo(boolean estado) {
        nome_usuarioTextField.setEnabled(estado);
        cargoComboBox.setEnabled(estado);
        senhaPasswordField.setEnabled(estado);
        confirma_senhaPasswordField.setEnabled(estado);
        eliminarButton.setEnabled(estado);
        gravarButton.setEnabled(estado);
        editar_Button.setEnabled(estado);
    }

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        int eliminar = JOptionPane.showConfirmDialog(null, "Deseja realmente apagar este registro", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (eliminar == JOptionPane.YES_OPTION) {
            String mensagem_erro = controlador.removerUsuário(nome_usuarioTextField.getText());

            if (mensagem_erro != null) {
                JOptionPane.showMessageDialog(this, mensagem_erro, "ERRO", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Usuário " + nome_usuarioTextField.getText() + " eliminado com sucesso", "OK", JOptionPane.INFORMATION_MESSAGE);
                limpa();
                eliminarButton.setEnabled(false);
                editar_Button.setEnabled(false);

            }
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
        setEdição(true);
        editarSalvar();
        limpa();
        setAtivo(true);
        nome_usuarioTextField.grabFocus();
        novoButton.setEnabled(false);
        eliminarButton.setEnabled(false);
        consultarButton.setEnabled(false);
        editar_Button.setEnabled(false);
        cancelaButton.setEnabled(true);
        cod_usuarioTextField.setText(Usuario.id());
    }//GEN-LAST:event_novoButtonActionPerformed

    static public void mostraDados(Usuario usuario) {
        limpa();
        setAtivo(true);
        gravarButton.setEnabled(false);
        cod_usuarioTextField.setText(String.valueOf(usuario.getCódigo()));
        nome_usuarioTextField.setText(usuario.getNome());
        cargoComboBox.setSelectedItem(FichaCadastro.Cargo.valueOf(usuario.getCargo()));
        senhaPasswordField.setText(usuario.getSenha());
        confirma_senhaPasswordField.setText(usuario.getSenha());
        setEdição(false);
        editarSalvar();

    }

    private boolean confereSenhaIguais() {
        if (senhaPasswordField.getText().equals(confirma_senhaPasswordField.getText())) {
            return true;
        } else {
            return false;
        }
    }

    private void consultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarButtonActionPerformed
        JanelaConsulta<Usuario> user = new JanelaConsulta<Usuario>(new Usuario());
            user.setTitle("Usuário");
            user.setVisible(true);
        limpa();
    }//GEN-LAST:event_consultarButtonActionPerformed

    private void gravarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarButtonActionPerformed
        consultarButton.setEnabled(true);
        cancelaButton.setEnabled(false);
        String mensagem_erro = null;

        Usuario usuário = new Usuario(Integer.valueOf(cod_usuarioTextField.getText()).intValue(),
                nome_usuarioTextField.getText(), senhaPasswordField.getText(), cargoComboBox.getSelectedItem().toString());

        if (!dadosOK(usuário)) {
            mensagem_erro = "Não pode conter registros em branco";
        } else if (!confereSenhaIguais()) {
            mensagem_erro = "Senhas não conferem";
        } else {
            mensagem_erro = controlador.inserirUsuário(usuário);
        }
        if (mensagem_erro != null) {
            JOptionPane.showMessageDialog(this, mensagem_erro, "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, nome_usuarioTextField.getText() + " Cadastrado com sucesso");
        }

        limpa();
        setAtivo(false);
        novoButton.setEnabled(true);
    }//GEN-LAST:event_gravarButtonActionPerformed
    public static boolean dadosOK(Usuario usuário) {
        if ((!usuário.getNome().equals(""))
                && (!usuário.getSenha().equals(""))
                && (!confirma_senhaPasswordField.equals(""))) {
            return true;
        } else {
            return false;
        }
    }
    private void editar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_ButtonActionPerformed
        editar_Button.setVisible(false);
        salvarButton.setVisible(true);
        nome_usuarioTextField.grabFocus();
        setEdição(true);
    }//GEN-LAST:event_editar_ButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        Usuario usuário = new Usuario(Integer.valueOf(cod_usuarioTextField.getText()).intValue(),
                nome_usuarioTextField.getText(), senhaPasswordField.getText(), cargoComboBox.getSelectedItem().toString());
        String mensagem_erro;
        if (!dadosOK(usuário)) {
            mensagem_erro = "Não pode conter registros em branco";
        } else if (!confereSenhaIguais()) {
            mensagem_erro = "Senhas não conferem";
        } else {
            mensagem_erro = controlador.alterarUsuário(usuário);
        }
        if (mensagem_erro != null) {
            JOptionPane.showMessageDialog(this, mensagem_erro, "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, nome_usuarioTextField.getText() + " alterado com sucesso");

        }
            setEdição(false);
            editarSalvar();
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void cancelaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaButtonActionPerformed
        limpa();
        setAtivo(false);
        novoButton.setEnabled(true);
        consultarButton.setEnabled(true);
        cancelaButton.setEnabled(false);
        gravarButton.setEnabled(false);
        editarSalvar();
    }//GEN-LAST:event_cancelaButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botões_fornecedorPanel;
    private javax.swing.JButton cancelaButton;
    public static javax.swing.JComboBox cargoComboBox;
    private javax.swing.JLabel cargoLabel;
    public static javax.swing.JTextField cod_usuarioTextField;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JLabel confirma_senhaLabel;
    public static javax.swing.JPasswordField confirma_senhaPasswordField;
    public static javax.swing.JButton consultarButton;
    private javax.swing.JPanel dadosPanel;
    public static javax.swing.JButton editar_Button;
    public static javax.swing.JButton eliminarButton;
    public static javax.swing.JButton gravarButton;
    private javax.swing.JLabel nomeLabel;
    public static javax.swing.JTextField nome_usuarioTextField;
    public static javax.swing.JButton novoButton;
    public static javax.swing.JButton salvarButton;
    private javax.swing.JLabel senhaLabel;
    public static javax.swing.JPasswordField senhaPasswordField;
    // End of variables declaration//GEN-END:variables
}
