/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import controle.ControladorCadastroFornecedor;
import controle.buscaCEP;
import entidade.FichaCadastro;
import entidade.Fornecedor;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MARCOANTONIO
 */
public class JanelaCadastroFornecedor extends javax.swing.JFrame {

    ControladorCadastroFornecedor controlador;
    static boolean isActive;

    /**
     * Creates new form JanelaCadastroFornecedor
     */
    public JanelaCadastroFornecedor(ControladorCadastroFornecedor controlador) {
        initComponents();
        setLocationRelativeTo(null);
        this.controlador = controlador;
        salvarButton.setVisible(false);
        isActive = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dadosPanel = new javax.swing.JPanel();
        codigo_fornecedorLabel = new javax.swing.JLabel();
        cnpjLabel = new javax.swing.JLabel();
        nome_fornecedorLabel = new javax.swing.JLabel();
        cod_fornecedorTextField = new javax.swing.JTextField();
        nome_fornecedorTextField = new javax.swing.JTextField();
        email_fornecedorLabel = new javax.swing.JLabel();
        email_fornecedorTextField = new javax.swing.JTextField();
        botões_fornecedorPanel = new javax.swing.JPanel();
        eliminarButton = new javax.swing.JButton();
        novoButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        gravarButton = new javax.swing.JButton();
        editar_Button = new javax.swing.JButton();
        salvarButton = new javax.swing.JButton();
        cancelaButton = new javax.swing.JButton();
        cnpjFormattedTextField = new javax.swing.JFormattedTextField();
        endereço_fornecedorPanel = new javax.swing.JPanel();
        ruaLabel = new javax.swing.JLabel();
        ruaTextField = new javax.swing.JTextField();
        numeroLabel = new javax.swing.JLabel();
        numeroTextField = new javax.swing.JTextField();
        bairroLabel = new javax.swing.JLabel();
        bairroTextField = new javax.swing.JTextField();
        cidadeLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        estadoComboBox = new javax.swing.JComboBox();
        cepLabel = new javax.swing.JLabel();
        cepFormattedTextField = new javax.swing.JFormattedTextField();
        telefoneLabel = new javax.swing.JLabel();
        cidadeTextField = new javax.swing.JTextField();
        telefoneFormattedTextField = new javax.swing.JFormattedTextField();
        buscacepjLabel = new javax.swing.JLabel();
        dataFormattedTextField = new javax.swing.JFormattedTextField();
        dataLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        dadosPanel.setBackground(new java.awt.Color(255, 255, 255));
        dadosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Cadastro de Fornecedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        codigo_fornecedorLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        codigo_fornecedorLabel.setText("Codigo");

        cnpjLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cnpjLabel.setText("Cnpj");

        nome_fornecedorLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nome_fornecedorLabel.setText("Nome");

        cod_fornecedorTextField.setEditable(false);
        cod_fornecedorTextField.setEnabled(false);

        nome_fornecedorTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nome_fornecedorTextField.setEnabled(false);
        nome_fornecedorTextField.setFocusCycleRoot(true);
        nome_fornecedorTextField.setSelectedTextColor(new java.awt.Color(255, 204, 0));

        email_fornecedorLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        email_fornecedorLabel.setText("Email");

        email_fornecedorTextField.setEnabled(false);

        botões_fornecedorPanel.setBackground(new java.awt.Color(255, 255, 255));

        eliminarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.setEnabled(false);
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        novoButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        novoButton.setText("Novo");
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });

        consultarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarButtonActionPerformed(evt);
            }
        });

        gravarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gravarButton.setText("Gravar");
        gravarButton.setEnabled(false);
        gravarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravarButtonActionPerformed(evt);
            }
        });

        editar_Button.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editar_Button.setText("Editar");
        editar_Button.setEnabled(false);
        editar_Button.setMaximumSize(new java.awt.Dimension(63, 23));
        editar_Button.setMinimumSize(new java.awt.Dimension(63, 23));
        editar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_ButtonActionPerformed(evt);
            }
        });

        salvarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        cancelaButton.setText("Cancela");
        cancelaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botões_fornecedorPanelLayout = new javax.swing.GroupLayout(botões_fornecedorPanel);
        botões_fornecedorPanel.setLayout(botões_fornecedorPanelLayout);
        botões_fornecedorPanelLayout.setHorizontalGroup(
            botões_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botões_fornecedorPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(novoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gravarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelaButton))
        );
        botões_fornecedorPanelLayout.setVerticalGroup(
            botões_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botões_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(gravarButton)
                .addComponent(consultarButton)
                .addComponent(editar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(salvarButton)
                .addComponent(eliminarButton)
                .addComponent(novoButton)
                .addComponent(cancelaButton))
        );

        try {
            cnpjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cnpjFormattedTextField.setEnabled(false);
        cnpjFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjFormattedTextFieldActionPerformed(evt);
            }
        });

        endereço_fornecedorPanel.setBackground(new java.awt.Color(255, 255, 255));
        endereço_fornecedorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 10), new java.awt.Color(0, 0, 0))); // NOI18N

        ruaLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ruaLabel.setText("Rua");

        ruaTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ruaTextField.setEnabled(false);
        ruaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaTextFieldActionPerformed(evt);
            }
        });

        numeroLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numeroLabel.setText("Nº");

        numeroTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numeroTextField.setEnabled(false);

        bairroLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bairroLabel.setText("Bairro");

        bairroTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bairroTextField.setEnabled(false);

        cidadeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cidadeLabel.setText("Cidade");

        estadoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        estadoLabel.setText("Estado");

        estadoComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        estadoComboBox.setModel(new DefaultComboBoxModel(FichaCadastro.UF.values()));
        estadoComboBox.setEnabled(false);
        estadoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoComboBoxActionPerformed(evt);
            }
        });

        cepLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cepLabel.setText("Cep");

        try {
            cepFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cepFormattedTextField.setEnabled(false);

        telefoneLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        telefoneLabel.setText("Telefone");

        cidadeTextField.setEnabled(false);

        try {
            telefoneFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneFormattedTextField.setEnabled(false);
        telefoneFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneFormattedTextFieldActionPerformed(evt);
            }
        });

        buscacepjLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buscacepjLabel.setForeground(new java.awt.Color(0, 0, 255));
        buscacepjLabel.setText("Buscar Endereço");
        buscacepjLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        buscacepjLabel.setEnabled(false);
        buscacepjLabel.setText("<html><u>Buscar Endereço</u></html>");
        buscacepjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscacepjLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout endereço_fornecedorPanelLayout = new javax.swing.GroupLayout(endereço_fornecedorPanel);
        endereço_fornecedorPanel.setLayout(endereço_fornecedorPanelLayout);
        endereço_fornecedorPanelLayout.setHorizontalGroup(
            endereço_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endereço_fornecedorPanelLayout.createSequentialGroup()
                .addGroup(endereço_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(endereço_fornecedorPanelLayout.createSequentialGroup()
                        .addComponent(bairroLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(endereço_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(endereço_fornecedorPanelLayout.createSequentialGroup()
                                .addComponent(telefoneLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(endereço_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(endereço_fornecedorPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cidadeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(endereço_fornecedorPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(estadoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(endereço_fornecedorPanelLayout.createSequentialGroup()
                        .addGroup(endereço_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(endereço_fornecedorPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(ruaLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, endereço_fornecedorPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cepLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(endereço_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(endereço_fornecedorPanelLayout.createSequentialGroup()
                                .addComponent(cepFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscacepjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(endereço_fornecedorPanelLayout.createSequentialGroup()
                                .addComponent(ruaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(numeroLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        endereço_fornecedorPanelLayout.setVerticalGroup(
            endereço_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endereço_fornecedorPanelLayout.createSequentialGroup()
                .addGroup(endereço_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cepLabel)
                    .addComponent(cepFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscacepjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(endereço_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaLabel)
                    .addComponent(ruaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroLabel)
                    .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(endereço_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(endereço_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estadoLabel))
                    .addGroup(endereço_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bairroLabel)
                        .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(endereço_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneLabel)
                    .addComponent(cidadeLabel)))
        );

        dataFormattedTextField.setEditable(false);
        dataFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        dataFormattedTextField.setEnabled(false);
        dataFormattedTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        dataLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataLabel.setText("Data de Cadastro");

        javax.swing.GroupLayout dadosPanelLayout = new javax.swing.GroupLayout(dadosPanel);
        dadosPanel.setLayout(dadosPanelLayout);
        dadosPanelLayout.setHorizontalGroup(
            dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPanelLayout.createSequentialGroup()
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botões_fornecedorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endereço_fornecedorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(dadosPanelLayout.createSequentialGroup()
                                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome_fornecedorLabel)
                                    .addComponent(codigo_fornecedorLabel)
                                    .addComponent(email_fornecedorLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome_fornecedorTextField)
                                    .addGroup(dadosPanelLayout.createSequentialGroup()
                                        .addComponent(cod_fornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dataLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dataFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(dadosPanelLayout.createSequentialGroup()
                                                .addComponent(cnpjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosPanelLayout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(cnpjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(43, 43, 43))
                                    .addComponent(email_fornecedorTextField))))))
                .addContainerGap())
        );
        dadosPanelLayout.setVerticalGroup(
            dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cod_fornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codigo_fornecedorLabel)
                        .addComponent(dataFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataLabel))
                    .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(cnpjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cnpjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_fornecedorLabel)
                    .addComponent(nome_fornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_fornecedorLabel)
                    .addComponent(email_fornecedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endereço_fornecedorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botões_fornecedorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dadosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dadosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static boolean dadosOK(Fornecedor fornecedor) {
        if ((!fornecedor.getNome().equals(""))
                && (!fornecedor.getN_documento().equals(""))
                && (!fornecedor.getEmail().equals(""))
                && (!fornecedor.getEndereço().equals(""))
                && (!fornecedor.getBairro().equals(""))
                && (fornecedor.getNumero() >= 0)
                && (fornecedor.getCódigo() >= 0)
                && (!fornecedor.getCep().equals(""))
                && (!fornecedor.getTelefone().equals(""))
                && (!fornecedor.getCidade().equals(""))) {
            return true;
        } else {
            return false;
        }
    }

    public static void limpa() {
        dataFormattedTextField.setText("");
        cod_fornecedorTextField.setText("");
        nome_fornecedorTextField.setText("");
        cnpjFormattedTextField.setText("");
        email_fornecedorTextField.setText("");
        ruaTextField.setText("");
        numeroTextField.setText("");
        bairroTextField.setText("");
        cepFormattedTextField.setText("");
        telefoneFormattedTextField.setText("");
        cidadeTextField.setText("");
        estadoComboBox.setSelectedIndex(0);
    }

    public static void editarSalvar() {
        salvarButton.setVisible(false);
        editar_Button.setVisible(true);
    }

    public static void setEdição(boolean estado) {
        cod_fornecedorTextField.setEditable(estado);
        dataFormattedTextField.setEditable(estado);
        nome_fornecedorTextField.setEditable(estado);
        cnpjFormattedTextField.setEditable(estado);
        email_fornecedorTextField.setEditable(estado);
        ruaTextField.setEditable(estado);
        numeroTextField.setEditable(estado);
        bairroTextField.setEditable(estado);
        estadoComboBox.setEnabled(estado);
        cepFormattedTextField.setEditable(estado);
        telefoneFormattedTextField.setEditable(estado);
        cidadeTextField.setEditable(estado);
    }
    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        int eliminar = JOptionPane.showConfirmDialog(null, "Deseja realmente apagar este registro", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (eliminar == JOptionPane.YES_OPTION) {
            String mensagem_erro = controlador.removerFornecedor(Integer.valueOf(cod_fornecedorTextField.getText()).intValue());

            if (mensagem_erro != null) {
                JOptionPane.showMessageDialog(this, mensagem_erro, "ERRO", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Fornecedor " + nome_fornecedorTextField.getText() + " eliminado com sucesso", "OK", JOptionPane.INFORMATION_MESSAGE);
                limpa();
                eliminarButton.setEnabled(false);
                editar_Button.setEnabled(false);

            }
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed
    public static void setAtivo(boolean estado) {
        cod_fornecedorTextField.setEnabled(estado);
        dataFormattedTextField.setEnabled(estado);
        nome_fornecedorTextField.setEnabled(estado);
        cnpjFormattedTextField.setEnabled(estado);
        email_fornecedorTextField.setEnabled(estado);
        ruaTextField.setEnabled(estado);
        numeroTextField.setEnabled(estado);
        bairroTextField.setEnabled(estado);
        estadoComboBox.setEnabled(estado);
        cepFormattedTextField.setEnabled(estado);
        telefoneFormattedTextField.setEnabled(estado);
        cidadeTextField.setEnabled(estado);
        editar_Button.setEnabled(estado);
        eliminarButton.setEnabled(estado);
        gravarButton.setEnabled(estado);
    }
    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
        setEdição(true);
        editarSalvar();
        limpa();
        setAtivo(true);
        dataFormattedTextField.setText(FichaCadastro.getDataAtual());
        cnpjFormattedTextField.grabFocus();
        novoButton.setEnabled(false);
        eliminarButton.setEnabled(false);
        consultarButton.setEnabled(false);
        editar_Button.setEnabled(false);
        cancelaButton.setEnabled(true);
        cod_fornecedorTextField.setText(Fornecedor.id());
        buscacepjLabel.setEnabled(true);
    }//GEN-LAST:event_novoButtonActionPerformed
    static public void mostraDados(Fornecedor fornecedor) {
        limpa();
        setAtivo(true);
        gravarButton.setEnabled(false);
        cod_fornecedorTextField.setText(String.valueOf(fornecedor.getCódigo()));
        dataFormattedTextField.setText(fornecedor.getData_cadastro());
        nome_fornecedorTextField.setText(fornecedor.getNome());
        email_fornecedorTextField.setText(fornecedor.getEmail());
        ruaTextField.setText(fornecedor.getEndereço());
        numeroTextField.setText(String.valueOf(fornecedor.getNumero()));
        bairroTextField.setText(fornecedor.getBairro());
        estadoComboBox.setSelectedItem(FichaCadastro.UF.valueOf(fornecedor.getEstado()));
        cepFormattedTextField.setText(fornecedor.getCep());
        telefoneFormattedTextField.setText(fornecedor.getTelefone());
        cidadeTextField.setText(fornecedor.getCidade());
        cnpjFormattedTextField.setText(fornecedor.getN_documento());
        setEdição(false);
        editarSalvar();

    }
    private void consultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarButtonActionPerformed
        new JanelaConsultaFornecedor().setVisible(true);
        limpa();
    }//GEN-LAST:event_consultarButtonActionPerformed

    private void gravarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarButtonActionPerformed
        consultarButton.setEnabled(true);
        cancelaButton.setEnabled(false);
        String mensagem_erro = null;
        if (numeroTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Não pode conter registros em branco", "Atenção", JOptionPane.WARNING_MESSAGE);

        }
        Fornecedor fornecedor = new Fornecedor(Integer.valueOf(cod_fornecedorTextField.getText()).intValue(),
                Integer.valueOf(numeroTextField.getText()).intValue(), nome_fornecedorTextField.getText(), dataFormattedTextField.getText(), cnpjFormattedTextField.getText(),
                ruaTextField.getText(), bairroTextField.getText(), telefoneFormattedTextField.getText(),
                cepFormattedTextField.getText(), estadoComboBox.getSelectedItem().toString(),
                cidadeTextField.getText(), email_fornecedorTextField.getText());

        if (!dadosOK(fornecedor)) {
            mensagem_erro = "Não pode conter registros em branco";
        } else {
            mensagem_erro = controlador.inserirFornecedor(fornecedor);
        }
        if (mensagem_erro != null) {
            JOptionPane.showMessageDialog(this, mensagem_erro, "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, nome_fornecedorTextField.getText() + " Cadastrado com sucesso");
        }

        limpa();
        setAtivo(false);
        novoButton.setEnabled(true);
        estadoComboBox.setSelectedIndex(0);

    }//GEN-LAST:event_gravarButtonActionPerformed

    private void editar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_ButtonActionPerformed
        editar_Button.setVisible(false);
        salvarButton.setVisible(true);
        cod_fornecedorTextField.setEditable(false);
        nome_fornecedorTextField.grabFocus();
        setEdição(true);
    }//GEN-LAST:event_editar_ButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        Fornecedor fornecedor = new Fornecedor(Integer.valueOf(cod_fornecedorTextField.getText()).intValue(),
                Integer.valueOf(numeroTextField.getText()).intValue(), nome_fornecedorTextField.getText(), dataFormattedTextField.getText(), cnpjFormattedTextField.getText(),
                ruaTextField.getText(), bairroTextField.getText(), telefoneFormattedTextField.getText(),
                cepFormattedTextField.getText(), estadoComboBox.getSelectedItem().toString(),
                cidadeTextField.getText(), email_fornecedorTextField.getText());
        String mensagem_erro;
        if (!dadosOK(fornecedor)) {
            mensagem_erro = "Não pode conter registros em branco";
        } else {
            mensagem_erro = controlador.alterarFornecedor(fornecedor);
        }
        if (mensagem_erro != null) {
            JOptionPane.showMessageDialog(this, mensagem_erro, "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, nome_fornecedorTextField.getText() + " alterado com sucesso");
        }

        setEdição(false);
        editarSalvar();
    }//GEN-LAST:event_salvarButtonActionPerformed

    private void cancelaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaButtonActionPerformed
        limpa();
        setAtivo(false);
        novoButton.setEnabled(true);
        consultarButton.setEnabled(true);
        cancelaButton.setEnabled(false);
        gravarButton.setEnabled(false);
        buscacepjLabel.setEnabled(false);
        editarSalvar();
    }//GEN-LAST:event_cancelaButtonActionPerformed

    private void cnpjFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjFormattedTextFieldActionPerformed
    }//GEN-LAST:event_cnpjFormattedTextFieldActionPerformed

    private void ruaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaTextFieldActionPerformed

    private void estadoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoComboBoxActionPerformed
    }//GEN-LAST:event_estadoComboBoxActionPerformed

    private void telefoneFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneFormattedTextFieldActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void buscacepjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscacepjLabelMouseClicked
        String cep = cepFormattedTextField.getText().replace(".", "").replace("-", "");
        if (cep.equals("        ")) {
            JOptionPane.showMessageDialog(this, "CEP não informado");
        } else {
            try {
                if (buscaCEP.existe(cep)) {
                    ruaTextField.setText(buscaCEP.getEndereco(cep).replace("Ã£", "ã"));
                    bairroTextField.setText(buscaCEP.getBairro(cep).replace("Ã£", "ã"));
                    estadoComboBox.setSelectedItem(FichaCadastro.UF.valueOf(buscaCEP.getUF(cep)));
                    cidadeTextField.setText(buscaCEP.getCidade(cep).replace("Ã£", "ã"));

                } else {
                    JOptionPane.showMessageDialog(this,"Cep "+cep+" não encontrado ");
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao buscar endereço: " + ex);
            }

        }
    }//GEN-LAST:event_buscacepjLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bairroLabel;
    public static javax.swing.JTextField bairroTextField;
    private javax.swing.JPanel botões_fornecedorPanel;
    public static javax.swing.JLabel buscacepjLabel;
    private javax.swing.JButton cancelaButton;
    public static javax.swing.JFormattedTextField cepFormattedTextField;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JLabel cidadeLabel;
    public static javax.swing.JTextField cidadeTextField;
    public static javax.swing.JFormattedTextField cnpjFormattedTextField;
    public static javax.swing.JLabel cnpjLabel;
    public static javax.swing.JTextField cod_fornecedorTextField;
    private javax.swing.JLabel codigo_fornecedorLabel;
    public static javax.swing.JButton consultarButton;
    private javax.swing.JPanel dadosPanel;
    public static javax.swing.JFormattedTextField dataFormattedTextField;
    private javax.swing.JLabel dataLabel;
    public static javax.swing.JButton editar_Button;
    public static javax.swing.JButton eliminarButton;
    private javax.swing.JLabel email_fornecedorLabel;
    public static javax.swing.JTextField email_fornecedorTextField;
    private javax.swing.JPanel endereço_fornecedorPanel;
    public static javax.swing.JComboBox estadoComboBox;
    private javax.swing.JLabel estadoLabel;
    public static javax.swing.JButton gravarButton;
    private javax.swing.JLabel nome_fornecedorLabel;
    public static javax.swing.JTextField nome_fornecedorTextField;
    public static javax.swing.JButton novoButton;
    private javax.swing.JLabel numeroLabel;
    public static javax.swing.JTextField numeroTextField;
    private javax.swing.JLabel ruaLabel;
    public static javax.swing.JTextField ruaTextField;
    public static javax.swing.JButton salvarButton;
    public static javax.swing.JFormattedTextField telefoneFormattedTextField;
    private javax.swing.JLabel telefoneLabel;
    // End of variables declaration//GEN-END:variables
}
