/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import entidade.Fornecedor;
import entidade.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author MARCOANTONIO
 */
public class JanelaConsultaProduto extends javax.swing.JFrame {

    /**
     * Creates new form JanelaConsultaCliente
     */
    public JanelaConsultaProduto() {
        initComponents();
        ArrayList<Produto> produtos = Produto.visãoTabela();
        if (produtos == null) {
            JOptionPane.showMessageDialog(this, "Erro ao recuperar os dados");
        } else {

            ModeloTabela modelo = new ModeloTabela(new String[]{"Código", "Decrição", "Estoque", "R$ Preço", "Marca"}, produtos.size(), 5);

            for (int i = 0; i < produtos.size(); i++) {
                modelo.setValueAt(produtos.get(i).getCódigo(), i, 0);
                modelo.setValueAt(produtos.get(i).getNome(), i, 1);
                modelo.setValueAt(produtos.get(i).getEstoque(), i, 2);
                modelo.setValueAt(produtos.get(i).getPreço_venda(), i, 3);
                modelo.setValueAt(produtos.get(i).getMarca(), i, 4);

            }
            consulta_ProdutoTable.setModel(modelo);
            consulta_ProdutoTable.getColumnModel().getColumn(0).setMinWidth(50);
            consulta_ProdutoTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            consulta_ProdutoTable.getColumnModel().getColumn(0).setMaxWidth(50);

            consulta_ProdutoTable.getColumnModel().getColumn(1).setMinWidth(600);
            consulta_ProdutoTable.getColumnModel().getColumn(1).setPreferredWidth(600);
            consulta_ProdutoTable.getColumnModel().getColumn(1).setMaxWidth(600);

            consulta_ProdutoTable.getColumnModel().getColumn(2).setMinWidth(70);
            consulta_ProdutoTable.getColumnModel().getColumn(2).setPreferredWidth(70);
            consulta_ProdutoTable.getColumnModel().getColumn(2).setMaxWidth(70);

            consulta_ProdutoTable.getColumnModel().getColumn(3).setMinWidth(70);
            consulta_ProdutoTable.getColumnModel().getColumn(3).setPreferredWidth(70);
            consulta_ProdutoTable.getColumnModel().getColumn(3).setMaxWidth(70);

            consulta_ProdutoTable.getColumnModel().getColumn(4).setMinWidth(85);
            consulta_ProdutoTable.getColumnModel().getColumn(4).setPreferredWidth(85);
            consulta_ProdutoTable.getColumnModel().getColumn(4).setMaxWidth(85);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consulta_ProdutoTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        consultaProdutoTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        total_clientesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        consulta_ProdutoTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        consulta_ProdutoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        consulta_ProdutoTable.setGridColor(new java.awt.Color(255, 255, 255));
        consulta_ProdutoTable.getTableHeader().setReorderingAllowed(false);
        consulta_ProdutoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                consulta_ProdutoTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(consulta_ProdutoTable);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Pesquisa Nome");

        consultaProdutoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaProdutoTextFieldActionPerformed(evt);
            }
        });
        consultaProdutoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                consultaProdutoTextFieldKeyReleased(evt);
            }
        });

        jButton1.setText("Cancela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Total clientes cadastrados");

        total_clientesLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        total_clientesLabel.setForeground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultaProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 367, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total_clientesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(consultaProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(total_clientesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consulta_ProdutoTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consulta_ProdutoTableMousePressed
        if (evt.getClickCount() == 2) {
            int linha = consulta_ProdutoTable.getSelectedRow();
            int colunaCod = 0;
            String codigo_temp = consulta_ProdutoTable.getValueAt(linha, colunaCod).toString();
            int codigo = Integer.valueOf(codigo_temp).intValue();
            Fornecedor fornecedor = Fornecedor.buscarFornecedor(codigo);
            Produto produto = Produto.buscarProduto(codigo);
            if (getTitle().equals("Consulta Produto")) {
                JanelaCadastroProduto.mostraDados(produto);
            }else if (getTitle().equals("Selecione o Produto")){
                JanelaVenda.mostraDadosProduto(produto);
            }
            

            dispose();
        }
    }//GEN-LAST:event_consulta_ProdutoTableMousePressed

    private void consultaProdutoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaProdutoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultaProdutoTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void consultaProdutoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultaProdutoTextFieldKeyReleased
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(consulta_ProdutoTable.getModel());
        consulta_ProdutoTable.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter(consultaProdutoTextField.getText().toUpperCase(), 1));
    }//GEN-LAST:event_consultaProdutoTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaConsultaProduto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField consultaProdutoTextField;
    private javax.swing.JTable consulta_ProdutoTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel total_clientesLabel;
    // End of variables declaration//GEN-END:variables
}
