/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import static controle.ImportaçãoXML.getNF;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.Namespace;
import org.jdom2.input.SAXBuilder;

/**
 *
 * @author MARCOANTONIO
 */
public class JanelaImportaçãoXML extends javax.swing.JFrame {

    /**
     * Creates new form JanelaImportaçãoXML
     */
    public JanelaImportaçãoXML() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        data_emissaoTextField = new javax.swing.JTextField();
        chaveFormattedTextField = new javax.swing.JFormattedTextField();
        serieTextField = new javax.swing.JTextField();
        nNFTextField = new javax.swing.JTextField();
        modTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        nomeFornTextField = new javax.swing.JTextField();
        cnpjTextField = new javax.swing.JTextField();
        lograTextField = new javax.swing.JTextField();
        numTextField = new javax.swing.JTextField();
        bairroTextField = new javax.swing.JTextField();
        cidadeTextField = new javax.swing.JTextField();
        ufTextField = new javax.swing.JTextField();
        cepTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        data_emissaoTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        data_emissaoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        data_emissaoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Data emissão"));

        chaveFormattedTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Chave de acesso"));
        chaveFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chaveFormattedTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        serieTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        serieTextField.setToolTipText("");
        serieTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Série"));

        nNFTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nNFTextField.setToolTipText("");
        nNFTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero NF"));

        modTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        modTextField.setToolTipText("");
        modTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo"));

        jButton1.setText("TESTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Fornecedor"));

        nomeFornTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomeFornTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));

        cnpjTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cnpjTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Cnpj"));

        lograTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lograTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Logradouro"));

        numTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        numTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero"));

        bairroTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bairroTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Bairro"));

        cidadeTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cidadeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Cidade"));

        ufTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ufTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("UF"));

        cepTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cepTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Cep"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeFornTextField)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cnpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lograTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cidadeTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ufTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(nomeFornTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cnpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lograTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ufTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chaveFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(data_emissaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nNFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(serieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 175, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chaveFormattedTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data_emissaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nNFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String getTagNF(Element element,int ch1, int ch2, int ch3, int ch4){
            return element.getChildren().get(ch1).getChildren().get(ch2).getChildren().get(ch3).getChildren().get(ch4).getText();
    }
    public String getTagEnd(Element element,int ch1, int ch2, int ch3, int ch4, int ch5){
        return element.getChildren().get(ch1).getChildren().get(ch2).getChildren().get(ch3).getChildren().get(ch4).getChildren().get(ch5).getText();
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        File file = new File("C:\\Users\\MARCOANTONIO\\Downloads\\1.xml");
        String chave, data_e, nNF, serie, modelo, nomeForn, cnpj, logra,
                numero, cep, bairro, cidade, uf;
            SAXBuilder builder = new SAXBuilder();
            try {
                Document document = builder.build(file);
                Element xml = (Element) document.getRootElement();
                chave = xml.getChildren().get(0).getChildren().get(0).getAttributeValue("Id").replace("NFe", "");
                data_e =  getTagNF(xml,0,0,0,7);
                nNF =  getTagNF(xml,0,0,0,6); 
                serie = getTagNF(xml,0,0,0,5);
                modelo = getTagNF(xml,0,0,0,4);
                nomeForn = getTagNF(xml,0,0,1,2);
                cnpj = getTagNF(xml,0,0,1,0);
                logra = getTagEnd(xml, 0, 0, 1, 3, 0);
                numero = getTagEnd(xml, 0, 0, 1, 3, 1);
                cep = getTagEnd(xml, 0, 0, 1, 3, 6);
                bairro = getTagEnd(xml, 0, 0, 1, 3, 2);
                cidade = getTagEnd(xml, 0, 0, 1, 3, 4);
                uf = getTagEnd(xml, 0, 0, 1, 3, 5);
                
                numTextField.setText(numero);
                cepTextField.setText(cep);
                bairroTextField.setText(bairro);
                cidadeTextField.setText(cidade);
                ufTextField.setText(uf);
                nNFTextField.setText(nNF);
                serieTextField.setText(serie);
                modTextField.setText(modelo);      
                chaveFormattedTextField.setText(chave);
                data_emissaoTextField.setText(data_e);
                nomeFornTextField.setText(nomeForn);
                cnpjTextField.setText(cnpj);
                lograTextField.setText(logra);
                
          //List det = xml.getChildren().get(0).getChildren().get(0).getChildren().;
                System.out.println( xml.getChildren().get(0).getChildren().get(0).getChildText("det"));
                
            } catch (JDOMException ex) {        
            Logger.getLogger(JanelaImportaçãoXML.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JanelaImportaçãoXML.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaImportaçãoXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaImportaçãoXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaImportaçãoXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaImportaçãoXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaImportaçãoXML().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairroTextField;
    private javax.swing.JTextField cepTextField;
    private javax.swing.JFormattedTextField chaveFormattedTextField;
    private javax.swing.JTextField cidadeTextField;
    private javax.swing.JTextField cnpjTextField;
    private javax.swing.JTextField data_emissaoTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lograTextField;
    private javax.swing.JTextField modTextField;
    private javax.swing.JTextField nNFTextField;
    private javax.swing.JTextField nomeFornTextField;
    private javax.swing.JTextField numTextField;
    private javax.swing.JTextField serieTextField;
    private javax.swing.JTextField ufTextField;
    // End of variables declaration//GEN-END:variables
}
