/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import entidade.Usuario;
import entidade.Vendedor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Marco Antonio
 */
public class JanelaCadastroVendedor extends javax.swing.JFrame {

    public JanelaCadastroVendedor() {
        initComponents();
        salvarButton.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dadosPanel = new javax.swing.JPanel();
        codigoLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        comissaoLabel = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        cod_vendedorTextField = new javax.swing.JTextField();
        nome_vendedorTextField = new javax.swing.JTextField();
        botões_fornecedorPanel = new javax.swing.JPanel();
        eliminarButton = new javax.swing.JButton();
        novoButton = new javax.swing.JButton();
        consultarButton = new javax.swing.JButton();
        gravarButton = new javax.swing.JButton();
        editar_Button = new javax.swing.JButton();
        salvarButton = new javax.swing.JButton();
        cancelaButton = new javax.swing.JButton();
        cod_usuarioTextField = new javax.swing.JTextField();
        nome_usuarioTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comissaoTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Vendedor");
        setResizable(false);

        dadosPanel.setBackground(new java.awt.Color(255, 255, 255));
        dadosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Cadastro de Vendedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 2, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        codigoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        codigoLabel.setText("Codigo");

        nomeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nomeLabel.setText("Nome");

        comissaoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comissaoLabel.setText("Comissão");

        usuarioLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usuarioLabel.setText("Usuário");

        cod_vendedorTextField.setEditable(false);
        cod_vendedorTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cod_vendedorTextField.setEnabled(false);

        nome_vendedorTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nome_vendedorTextField.setEnabled(false);

        botões_fornecedorPanel.setBackground(new java.awt.Color(255, 255, 255));

        eliminarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.setEnabled(false);
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        novoButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        novoButton.setText("Novo");
        novoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoButtonActionPerformed(evt);
            }
        });

        consultarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarButtonActionPerformed(evt);
            }
        });

        gravarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gravarButton.setText("Gravar");
        gravarButton.setEnabled(false);
        gravarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravarButtonActionPerformed(evt);
            }
        });

        editar_Button.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        editar_Button.setText("Editar");
        editar_Button.setEnabled(false);
        editar_Button.setMaximumSize(new java.awt.Dimension(63, 23));
        editar_Button.setMinimumSize(new java.awt.Dimension(63, 23));
        editar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_ButtonActionPerformed(evt);
            }
        });

        salvarButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        salvarButton.setText("Salvar");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        cancelaButton.setText("Cancela");
        cancelaButton.setEnabled(false);
        cancelaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botões_fornecedorPanelLayout = new javax.swing.GroupLayout(botões_fornecedorPanel);
        botões_fornecedorPanel.setLayout(botões_fornecedorPanelLayout);
        botões_fornecedorPanelLayout.setHorizontalGroup(
            botões_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botões_fornecedorPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(novoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gravarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelaButton))
        );
        botões_fornecedorPanelLayout.setVerticalGroup(
            botões_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botões_fornecedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(gravarButton)
                .addComponent(consultarButton)
                .addComponent(editar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(salvarButton)
                .addComponent(eliminarButton)
                .addComponent(novoButton)
                .addComponent(cancelaButton))
        );

        cod_usuarioTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cod_usuarioTextField.setEnabled(false);
        cod_usuarioTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cod_usuarioTextFieldFocusLost(evt);
            }
        });
        cod_usuarioTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cod_usuarioTextFieldKeyPressed(evt);
            }
        });

        nome_usuarioTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nome_usuarioTextField.setEnabled(false);
        nome_usuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_usuarioTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("%");

        comissaoTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        comissaoTextField1.setText("0,00");
        comissaoTextField1.setEnabled(false);
        comissaoTextField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comissaoTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comissaoTextField1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout dadosPanelLayout = new javax.swing.GroupLayout(dadosPanel);
        dadosPanel.setLayout(dadosPanelLayout);
        dadosPanelLayout.setHorizontalGroup(
            dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPanelLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(botões_fornecedorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(dadosPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(codigoLabel)
                    .addComponent(nomeLabel)
                    .addComponent(comissaoLabel)
                    .addComponent(usuarioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dadosPanelLayout.createSequentialGroup()
                        .addComponent(cod_usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nome_usuarioTextField))
                    .addComponent(nome_vendedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod_vendedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dadosPanelLayout.createSequentialGroup()
                        .addComponent(comissaoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGap(0, 207, Short.MAX_VALUE))
        );
        dadosPanelLayout.setVerticalGroup(
            dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel)
                    .addComponent(cod_vendedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(nome_vendedorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comissaoLabel)
                    .addComponent(jLabel1)
                    .addComponent(comissaoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioLabel)
                    .addComponent(cod_usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome_usuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(botões_fornecedorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dadosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dadosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void limpa() {
        nome_vendedorTextField.setText("");
        cod_vendedorTextField.setText("");
        comissaoTextField1.setText("0,00");
        cod_usuarioTextField.setText("");
        nome_usuarioTextField.setText("");
    }

    public static void editarSalvar() {
        salvarButton.setVisible(false);
        editar_Button.setVisible(true);
    }

    public static void setEdição(boolean estado) {
        nome_vendedorTextField.setEditable(estado);
        cod_vendedorTextField.setEditable(estado);
        comissaoTextField1.setEditable(estado);
        cod_usuarioTextField.setEditable(estado);
        nome_usuarioTextField.setEditable(estado);
    }

    public static void setAtivo(boolean estado) {
        nome_vendedorTextField.setEnabled(estado);
        cod_vendedorTextField.setEnabled(estado);
        comissaoTextField1.setEnabled(estado);
        cod_usuarioTextField.setEnabled(estado);
        nome_usuarioTextField.setEnabled(estado);

    }

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        int eliminar = JOptionPane.showConfirmDialog(null, "Deseja realmente apagar este registro", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (eliminar == JOptionPane.YES_OPTION) {
            String mensagem_erro = Vendedor.eleminarVendedor(Integer.valueOf(cod_vendedorTextField.getText()).intValue());

            if (mensagem_erro != null) {
                JOptionPane.showMessageDialog(this, mensagem_erro, "ERRO", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Vendedor " + nome_vendedorTextField.getText() + " eliminado com sucesso", "OK", JOptionPane.INFORMATION_MESSAGE);
                limpa();
                eliminarButton.setEnabled(false);
                editar_Button.setEnabled(false);

            }
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void novoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoButtonActionPerformed
        setEdição(true);
        editarSalvar();
        limpa();
        setAtivo(true);
        nome_vendedorTextField.grabFocus();
        novoButton.setEnabled(false);
        eliminarButton.setEnabled(false);
        consultarButton.setEnabled(false);
        editar_Button.setEnabled(false);
        cancelaButton.setEnabled(true);
        gravarButton.setEnabled(true);
        cod_vendedorTextField.setText(Vendedor.id());
    }//GEN-LAST:event_novoButtonActionPerformed

    static public void mostraDados(Vendedor vendedor) {
        limpa();
        setAtivo(true);
        if (vendedor == null) {
            JOptionPane.showMessageDialog(null, "Vendedor = NULL");
        } else {
            gravarButton.setEnabled(false);
            cod_vendedorTextField.setText(String.valueOf(vendedor.getCodigo()));
            nome_vendedorTextField.setText(vendedor.getNome());
            comissaoTextField1.setText(String.valueOf(vendedor.getComissao()));
            if (vendedor.getUsuario().getCódigo() == 0) {
                cod_usuarioTextField.setText("");
            } else {
                cod_usuarioTextField.setText(String.valueOf(vendedor.getUsuario().getCódigo()));
            }
            nome_usuarioTextField.setText(vendedor.getUsuario().getNome());
            setEdição(false);
            editar_Button.setEnabled(true);
            eliminarButton.setEnabled(true);
            editarSalvar();
        }
    }


    private void consultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarButtonActionPerformed
        JanelaConsulta<Vendedor> vendedor = new JanelaConsulta<Vendedor>(new Vendedor());
        vendedor.setTitle("Vendedor");
        vendedor.setVisible(true);
        limpa();
    }//GEN-LAST:event_consultarButtonActionPerformed

    private void gravarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarButtonActionPerformed
        consultarButton.setEnabled(true);
        cancelaButton.setEnabled(false);
        String mensagem_erro = null;
        Usuario usuario;
        if (cod_usuarioTextField.getText().equals("")) {
            usuario = new Usuario(0);
        } else {
            usuario = new Usuario(Integer.valueOf(cod_usuarioTextField.getText()));
        }

        Vendedor vendedor = new Vendedor(Integer.valueOf(cod_vendedorTextField.getText()).intValue(), nome_vendedorTextField.getText(), Float.valueOf(comissaoTextField1.getText().replace(",", ".")), usuario);

        if (!dadosOK(vendedor)) {
            mensagem_erro = "O campo nome é obrigatório";
        } else {
            mensagem_erro = Vendedor.inserirVendedor(vendedor);
        }
        if (mensagem_erro != null) {
            JOptionPane.showMessageDialog(this, mensagem_erro, "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, nome_vendedorTextField.getText() + " Cadastrado com sucesso");
            limpa();
            setAtivo(false);
            novoButton.setEnabled(true);
        }


    }//GEN-LAST:event_gravarButtonActionPerformed
    public static boolean dadosOK(Vendedor vendedor) {
        if ((!vendedor.getNome().equals(""))) {
            return true;
        } else {
            return false;
        }
    }
    private void editar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_ButtonActionPerformed
        editar_Button.setVisible(false);
        salvarButton.setVisible(true);
        nome_vendedorTextField.grabFocus();
        setEdição(true);
    }//GEN-LAST:event_editar_ButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        Usuario usuario = new Usuario(Integer.valueOf(cod_usuarioTextField.getText()));

        Vendedor vendedor = new Vendedor(Integer.valueOf(cod_vendedorTextField.getText()).intValue(), nome_vendedorTextField.getText(), Float.valueOf(comissaoTextField1.getText().replace(",", ".")), usuario);

        String mensagem_erro;
        if (!dadosOK(vendedor)) {
            mensagem_erro = "Nome do vendedor é obrigatorio";
        } else {
            mensagem_erro = Vendedor.alterarVendedor(vendedor);
        }
        if (mensagem_erro != null) {
            JOptionPane.showMessageDialog(this, mensagem_erro, "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, nome_vendedorTextField.getText() + " alterado com sucesso");
            setEdição(false);
            editarSalvar();
        }

    }//GEN-LAST:event_salvarButtonActionPerformed

    private void cancelaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaButtonActionPerformed
        limpa();
        setAtivo(false);
        novoButton.setEnabled(true);
        consultarButton.setEnabled(true);
        cancelaButton.setEnabled(false);
        gravarButton.setEnabled(false);
        editarSalvar();
    }//GEN-LAST:event_cancelaButtonActionPerformed

    private void nome_usuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_usuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_usuarioTextFieldActionPerformed

    private void cod_usuarioTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cod_usuarioTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            JanelaConsulta<Usuario> user = new JanelaConsulta<Usuario>(new Usuario());
            user.setTitle("Consulta Usuario");
            user.setVisible(true);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (cod_usuarioTextField.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Digite o código do Usuario");
                nome_usuarioTextField.setText("");
            } else {
                try {
                    Usuario user = Usuario.verificaUsuário(Integer.valueOf(cod_usuarioTextField.getText()));
                    nome_usuarioTextField.setText(user.getNome());
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, ex, "ERRO", JOptionPane.ERROR_MESSAGE);
                }
                nome_usuarioTextField.grabFocus();
            }
        }

    }//GEN-LAST:event_cod_usuarioTextFieldKeyPressed

    public static void mostraUsuario(Usuario usuario) {
        cod_usuarioTextField.setText(String.valueOf(usuario.getCódigo()));
        nome_usuarioTextField.grabFocus();
        try {
            Usuario user = Usuario.verificaUsuário(Integer.valueOf(cod_usuarioTextField.getText()));
            nome_usuarioTextField.setText(user.getNome());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex, "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void cod_usuarioTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cod_usuarioTextFieldFocusLost


    }//GEN-LAST:event_cod_usuarioTextFieldFocusLost

    private void comissaoTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comissaoTextField1FocusLost
        if (comissaoTextField1.getText().equals("")) {
            comissaoTextField1.setText("0,00");
        }
    }//GEN-LAST:event_comissaoTextField1FocusLost
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botões_fornecedorPanel;
    private javax.swing.JButton cancelaButton;
    public static javax.swing.JTextField cod_usuarioTextField;
    public static javax.swing.JTextField cod_vendedorTextField;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JLabel comissaoLabel;
    public static javax.swing.JFormattedTextField comissaoTextField1;
    public static javax.swing.JButton consultarButton;
    private javax.swing.JPanel dadosPanel;
    public static javax.swing.JButton editar_Button;
    public static javax.swing.JButton eliminarButton;
    public static javax.swing.JButton gravarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomeLabel;
    public static javax.swing.JTextField nome_usuarioTextField;
    public static javax.swing.JTextField nome_vendedorTextField;
    public static javax.swing.JButton novoButton;
    public static javax.swing.JButton salvarButton;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
