/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import entidade.Cliente;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author MARCOANTONIO
 */
public class JanelaConsulta<T> extends javax.swing.JFrame {

    T objeto;

    public JanelaConsulta(T objeto) {
        this.objeto = objeto;
        initComponents();
        setLocationRelativeTo(null);
        System.out.println();
        if (objeto instanceof Cliente) {
            ArrayList<Cliente> clientes = null;
            clientes = Cliente.visãoTabela();
            if (clientes == null) {
                JOptionPane.showMessageDialog(this, "Erro ao recuperar os dados");
            } else {
                tabelaCliente(clientes);
            }
        } else {
            System.out.println("NO OK ");
        }

    }

    private void tabelaCliente(ArrayList<Cliente> clientes) {
        ModeloTabela modelo = new ModeloTabela(new String[]{"Código", "Nome", "Cpf/Cnpj", "Data Cadastro"}, clientes.size(), 4);

        for (int i = 0; i < clientes.size(); i++) {
            modelo.setValueAt(clientes.get(i).getCódigo(), i, 0);
            modelo.setValueAt(clientes.get(i).getNome(), i, 1);
            modelo.setValueAt(clientes.get(i).getN_documento(), i, 2);
            modelo.setValueAt(clientes.get(i).getData_cadastro(), i, 3);

        }

        dadosTable.setModel(modelo);
        
        
        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dadosTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dadosTable.setAutoCreateRowSorter(true);
        dadosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        dadosTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dadosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dadosTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(dadosTable);

        jLabel1.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dadosTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dadosTableMousePressed
        if (evt.getClickCount() == 2) {
            int linha = dadosTable.getSelectedRow();
            int colunaCod = 0;
            String codigo_temp = dadosTable.getValueAt(linha, colunaCod).toString();
            int codigo = Integer.valueOf(codigo_temp).intValue();
            Cliente cliente = Cliente.buscarCliente(codigo);
            if (objeto instanceof Cliente) {
                if (getTitle().equalsIgnoreCase("Clientes")) {
                    JanelaCadastroCliente_.mostraDados(cliente);
                    dispose();
                } else if (getTitle().equalsIgnoreCase("Selecione o cliente para a venda")) {
                    JanelaVenda.mostraDadosCliente(cliente);
                    dispose();
                }
            }

        }

    }//GEN-LAST:event_dadosTableMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable dadosTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
